"""implement relationships

Revision ID: 062d664c5ebd
Revises: db6cbddfd5c3
Create Date: 2024-09-23 16:33:40.717093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062d664c5ebd'
down_revision = 'db6cbddfd5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('scientist_id', sa.Integer(), nullable=False))
    op.add_column('missions', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.alter_column('missions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(op.f('fk_missions_scientist_id_scientists'), 'missions', 'scientists', ['scientist_id'], ['id'])
    op.create_foreign_key(op.f('fk_missions_planet_id_planets'), 'missions', 'planets', ['planet_id'], ['id'])
    op.alter_column('scientists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scientists', 'field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scientists', 'field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scientists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('fk_missions_planet_id_planets'), 'missions', type_='foreignkey')
    op.drop_constraint(op.f('fk_missions_scientist_id_scientists'), 'missions', type_='foreignkey')
    op.alter_column('missions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('missions', 'planet_id')
    op.drop_column('missions', 'scientist_id')
    # ### end Alembic commands ###
